### ISSUE TITLE
Chapters missing

### ISSUE THREAD

**Issue by masteoo** [GladistonXD/perlego-download#1]
Hello, thanks for this extension!! I tried but in the saved html file some chapters are missing:(
Books in epub version are https://www.perlego.com/it/book/1536781/bine-ati-venit-corso-di-lingua-romena-livelli-a1b1-del-quadro-comune-europeo-di-riferimento-per-le-lingue-pdf

https://www.perlego.com/it/book/1978699/grammatica-ungherese-di-base-con-esercizi-e-soluzioni-pdf

**Comment by GladistonXD** [comment]
> Hello, thanks for this extension!! I tried but in the saved html file some chapters are missing:( Books in epub version are https://www.perlego.com/it/book/1536781/bine-ati-venit-corso-di-lingua-romena-livelli-a1b1-del-quadro-comune-europeo-di-riferimento-per-le-lingue-pdf
> 
> https://www.perlego.com/it/book/1978699/grammatica-ungherese-di-base-con-esercizi-e-soluzioni-pdf

**Hello, I hadn't dealt with such large files in ePUB, I released a fix to wait until the page loads.**

**Comment by masteoo** [comment]
> > Hello, thanks for this extension!! I tried but in the saved html file some chapters are missing:( Books in epub version are https://www.perlego.com/it/book/1536781/bine-ati-venit-corso-di-lingua-romena-livelli-a1b1-del-quadro-comune-europeo-di-riferimento-per-le-lingue-pdf
> > https://www.perlego.com/it/book/1978699/grammatica-ungherese-di-base-con-esercizi-e-soluzioni-pdf
> 
> **Hello, I hadn't dealt with such large files in ePUB, I released a fix to wait until the page loads.**

Thanks a lot but still doesn't work:( it stops at chapter 8.
I upoload .html file renamed .zip
Thanks
Telegram @ProseccoDoc[
[perlego.zip](https://github.com/GladistonXD/perlego-download/files/13252977/perlego.zip)
](url)

**Comment by masteoo** [comment]
> > Hello, thanks for this extension!! I tried but in the saved html file some chapters are missing:( Books in epub version are https://www.perlego.com/it/book/1536781/bine-ati-venit-corso-di-lingua-romena-livelli-a1b1-del-quadro-comune-europeo-di-riferimento-per-le-lingue-pdf
> > https://www.perlego.com/it/book/1978699/grammatica-ungherese-di-base-con-esercizi-e-soluzioni-pdf
> 
> **Hello, I hadn't dealt with such large files in ePUB, I released a fix to wait until the page loads.**

Did again but it always stops, sorry and thanks for your

**Comment by GladistonXD** [comment]
It's probably your connection, in `content.js` I wrote `const time = 3000`, you can put larger values so that it takes longer before changing pages in case of a slow connection. 3000 equals 3 seconds.
[perlego - 2023-11-03T143717.813.zip](https://github.com/GladistonXD/perlego-download/files/13253163/perlego.-.2023-11-03T143717.813.zip)

**Comment by masteoo** [comment]
> It's probably your connection, in `content.js` I wrote `const time = 3000`, you can put larger values so that it takes longer before changing pages in case of a slow connection. 3000 equals 3 seconds. [perlego - 2023-11-03T143717.813.zip](https://github.com/GladistonXD/perlego-download/files/13253163/perlego.-.2023-11-03T143717.813.zip)

Thanks for your reply... I put 15000 but still some chapters missing with another book too. I will try another wifi and original Chrome, not Kiwi. Thanks again
![Screenshot_20231103_191343_Kiwi Browser](https://github.com/GladistonXD/perlego-download/assets/120033556/2bb503da-8bac-47af-b068-29d175499329)

**Comment by masteoo** [comment]
> It's probably your connection, in `content.js` I wrote `const time = 3000`, you can put larger values so that it takes longer before changing pages in case of a slow connection. 3000 equals 3 seconds. [perlego - 2023-11-03T143717.813.zip](https://github.com/GladistonXD/perlego-download/files/13253163/perlego.-.2023-11-03T143717.813.zip)

In chrome on pc deskop with same connection was all ok! So there is a problem on my tab S8 with extension and kiwi app. Thank you for your help

**Comment by GladistonXD** [comment]
> > It's probably your connection, in `content.js` I wrote `const time = 3000`, you can put larger values so that it takes longer before changing pages in case of a slow connection. 3000 equals 3 seconds. [perlego - 2023-11-03T143717.813.zip](https://github.com/GladistonXD/perlego-download/files/13253163/perlego.-.2023-11-03T143717.813.zip)
> 
> In chrome on pc deskop with same connection was all ok! So there is a problem on my tab S8 with extension and kiwi app. Thank you for your help

I only did the tests based on the standard Chrome browser, other similar applications may interact differently with this automation, and I also didn't test all the possibilities, you may encounter some bugs depending on the book.

**Comment by MajidAmin112** [comment]
Whats the method to download book. please waiting for your respose.

**Comment by GladistonXD** [comment]
> Whats the method to download book. please waiting for your respose.

You need an active account, load the chrome extension then open the book and start the process, I updated the description, If the question was related to the system used, it is an automation that captures fragments of the root html, joins all the pages and transforms them into a new separate html.

**Comment by MajidAmin112** [comment]
There are missing lot of images which needs badly. what to do.
![Screenshot 2023-11-04 164403](https://github.com/GladistonXD/perlego-download/assets/124704274/07609e36-d24d-488a-8fba-8f3f5300248a)

**Comment by GladistonXD** [comment]
> There are missing lot of images which needs badly. what to do. ![Screenshot 2023-11-04 164403](https://user-images.githubusercontent.com/124704274/280463919-07609e36-d24d-488a-8fba-8f3f5300248a.png)

I sent the book ID so I can check

**Comment by MajidAmin112** [comment]
4265747

**Comment by GladistonXD** [comment]
> 4265747
![image](https://github.com/GladistonXD/perlego-download/assets/50533550/b6fa8b9c-64d4-4af7-913d-d45f497c1f23)

**Here it is normal, you need to have an internet connection when opening the images from the .html file, to use it offline you need to transform it into a PDF**

**Comment by masteoo** [comment]
@GladistonXD hello, sorry to disturb, do you think is possible to create a downloader Chrome extension also for this script? 
https://github.com/Leone25/bSmart-downloader
Thanks again
Tl.me @ProseccoDoc

**Comment by GladistonXD** [comment]
> @GladistonXD hello, sorry to disturb, do you think is possible to create a downloader Chrome extension also for this script? https://github.com/Leone25/bSmart-downloader Thanks again Tl.me @ProseccoDoc

Yes, it is possible, but it works with node.js which requires other repositories to work, implementing it as a chrome extension would not be viable depending on the final size, so much so that it does not include automatic PDF conversion, as it would need other repositories.

**Comment by masteoo** [comment]
> > @GladistonXD hello, sorry to disturb, do you think is possible to create a downloader Chrome extension also for this script? https://github.com/Leone25/bSmart-downloader Thanks again Tl.me @ProseccoDoc
> 
> Yes, it is possible, but it works with node.js which requires other repositories to work, implementing it as a chrome extension would not be viable depending on the final size, so much so that it does not include automatic PDF conversion, as it would need other repositories.

Oh understood, thanks a lot for your feedback. I found also this python script, maybe is easier (I have credentials if you need to test it:)
https://github.com/FelixFrog/pdfgrabber

**Comment by masteoo** [comment]
@GladistonXD hello, sorry to disturb, could you suggest me books or webpages where I can study how to convert py scripts to Chrome extensions in a easy way please? Thanks a lot..feel free to Telegram me

**Comment by GladistonXD** [comment]
> @GladistonXD hello, sorry to disturb, could you suggest me books or webpages where I can study how to convert py scripts to Chrome extensions in a easy way please? Thanks a lot..feel free to Telegram me

Hello, Chrome extensions are very limited, sometimes it is even possible to convert from py to javascript without having to import much, but for requests it is more complicated, in the case of my script it was not a conversion, I did an automation based on "Xpath ", you can do any type of automation on a website using Xpath.

**Comment by masteoo** [comment]
> > @GladistonXD hello, sorry to disturb, could you suggest me books or webpages where I can study how to convert py scripts to Chrome extensions in a easy way please? Thanks a lot..feel free to Telegram me
> 
> Hello, Chrome extensions are very limited, sometimes it is even possible to convert from py to javascript without having to import much, but for requests it is more complicated, in the case of my script it was not a conversion, I did an automation based on "Xpath ", you can do any type of automation on a website using Xpath.

@GladistonXD  Oh understand, thanks.. maybe too difficult for me:)

**Comment by masteoo** [comment]
@GladistonXD hello, sorry to disturb, could you create or tell me how to download epub or pdf of this book please? Chapters are 1686 😱. Thanks
https://en.readerexp.com/virginity-in-second-marriages-bd269.html

**Comment by masteoo** [comment]
@GladistonXD hello and Happy New Year, sorry to disturb, do u think is possible to create a similar app also for everand.com website? Thanks

**Comment by GladistonXD** [comment]
> everand.com

it is possible, however, Everland's image expiration time is 30 seconds, I would have to do something more complex to store the images locally, at the moment I have no plans to create a new extension, I only did this one out of necessity on the day and decided to share it.

**Comment by masteoo** [comment]
@GladistonXD ok no problem, thanks for your time. Now I have to find something that can translate eng epub into Ita,  nothing works

**Comment by GladistonXD** [comment]
Sometimes chrome own page translator works, but it is not 100% effective.

**Comment by masteoo** [comment]
@GladistonXD but I need to create a new Ita epub. Eng file is too long

**Comment by masteoo** [comment]
@GladistonXD @pedroggbcampos hello, sorry to disturb you, can I ask your support to adapt this tool to download epub from Gobi library? I can give u credentials in private if you want. 
Thanks for your time
My Telegram @ProseccoDoc
